services:
  redis:
    image: redis:7.4
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - redis-network
  ui:
    image: redis/redisinsight:2.54
    container_name: redisui
    ports:
      - 8080:5540
    volumes:
      - redisinsight-data:/data
    networks:
      - redis-network

volumes:
  redis-data:
  redisinsight-data:

networks:
  redis-network:
    driver: bridge
